# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dna_seaching(object):
    def setupUi(self, dna_seaching):
        dna_seaching.setObjectName("dna_seaching")
        dna_seaching.resize(969, 646)
        dna_seaching.setStyleSheet("")
        self.btn_browse = QtWidgets.QPushButton(parent=dna_seaching)
        self.btn_browse.setGeometry(QtCore.QRect(840, 50, 111, 41))
        self.btn_browse.setStyleSheet("color: white; font-size: 16px; font-weight: bold;  border: 2px solid purple; padding: 4px; background-image: url(5.jpg);")
        self.btn_browse.setObjectName("btn_browse")
        self.ed_pattern = QtWidgets.QLineEdit(parent=dna_seaching)
        self.ed_pattern.setGeometry(QtCore.QRect(10, 140, 811, 41))
        self.ed_pattern.setStyleSheet(" font-size: 20px;\n"
"color:black;")
        self.ed_pattern.setObjectName("ed_pattern")
        self.label_7 = QtWidgets.QLabel(parent=dna_seaching)
        self.label_7.setGeometry(QtCore.QRect(560, 480, 101, 31))
        self.label_7.setStyleSheet("color: white; font-size: 20px; font-weight: bold;padding:5px;")
        self.label_7.setObjectName("label_7")
        self.ed_text = QtWidgets.QLineEdit(parent=dna_seaching)
        self.ed_text.setGeometry(QtCore.QRect(10, 50, 811, 41))
        self.ed_text.setStyleSheet(" font-size: 20px;\n"
"color:black;")
        self.ed_text.setObjectName("ed_text")
        self.label = QtWidgets.QLabel(parent=dna_seaching)
        self.label.setGeometry(QtCore.QRect(10, 10, 931, 41))
        self.label.setStyleSheet("color: white; font-size: 20px; font-weight: bold;padding:5px;")
        self.label.setObjectName("label")
        self.label_6 = QtWidgets.QLabel(parent=dna_seaching)
        self.label_6.setGeometry(QtCore.QRect(560, 430, 131, 31))
        self.label_6.setStyleSheet("color: white; font-size: 20px; font-weight: bold;padding:5px;")
        self.label_6.setObjectName("label_6")
        self.lbl_outputt = QtWidgets.QLabel(parent=dna_seaching)
        self.lbl_outputt.setGeometry(QtCore.QRect(10, 350, 471, 271))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_outputt.setFont(font)
        self.lbl_outputt.setStyleSheet("border: 2px solid purple;\n"
"color:white;\n"
" font-size: 20px; font-weight: bold;background-image: url();")
        self.lbl_outputt.setText("")
        self.lbl_outputt.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_outputt.setObjectName("lbl_outputt")
        self.label_3 = QtWidgets.QLabel(parent=dna_seaching)
        self.label_3.setGeometry(QtCore.QRect(10, 100, 931, 31))
        self.label_3.setStyleSheet("color: white; font-size: 20px; font-weight: bold;background-image: url();")
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(parent=dna_seaching)
        self.label_5.setGeometry(QtCore.QRect(560, 370, 101, 41))
        self.label_5.setStyleSheet("color: white; font-size: 20px; font-weight: bold;padding:5px;")
        self.label_5.setObjectName("label_5")
        self.lbl_idx = QtWidgets.QLabel(parent=dna_seaching)
        self.lbl_idx.setGeometry(QtCore.QRect(700, 370, 251, 41))
        self.lbl_idx.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"color:black;\n"
" background-color:white;")
        self.lbl_idx.setText("")
        self.lbl_idx.setObjectName("lbl_idx")
        self.label_2 = QtWidgets.QLabel(parent=dna_seaching)
        self.label_2.setGeometry(QtCore.QRect(10, 190, 931, 31))
        self.label_2.setStyleSheet("color: white; font-size: 20px; font-weight: bold;background-image: url();")
        self.label_2.setObjectName("label_2")
        self.lbl_align = QtWidgets.QLabel(parent=dna_seaching)
        self.lbl_align.setGeometry(QtCore.QRect(700, 420, 251, 41))
        self.lbl_align.setStyleSheet("color:black;\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
" background-color:white;")
        self.lbl_align.setText("")
        self.lbl_align.setObjectName("lbl_align")
        self.cbox_algorithm = QtWidgets.QComboBox(parent=dna_seaching)
        self.cbox_algorithm.setGeometry(QtCore.QRect(10, 230, 811, 41))
        self.cbox_algorithm.setStyleSheet("color: black; font-size: 15px; background-image: url(); border: 2px solid gray; padding: 2px;")
        self.cbox_algorithm.setObjectName("cbox_algorithm")
        self.cbox_algorithm.addItem("")
        self.cbox_algorithm.addItem("")
        self.cbox_algorithm.addItem("")
        self.cbox_algorithm.addItem("")
        self.cbox_algorithm.addItem("")
        self.cbox_algorithm.addItem("")
        self.cbox_algorithm.addItem("")
        self.cbox_algorithm.addItem("")
        self.label_4 = QtWidgets.QLabel(parent=dna_seaching)
        self.label_4.setGeometry(QtCore.QRect(10, 290, 941, 41))
        self.label_4.setStyleSheet("color: white; font-size: 25px; font-weight: bold;padding:5px;\n"
"border: 1px solid purple;")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.btn_apply = QtWidgets.QPushButton(parent=dna_seaching)
        self.btn_apply.setGeometry(QtCore.QRect(540, 560, 301, 51))
        self.btn_apply.setStyleSheet("color: white; font-size: 20px; font-weight: bold;  border: 3px solid purple; ")
        self.btn_apply.setObjectName("btn_apply")
        self.lbl_skip = QtWidgets.QLabel(parent=dna_seaching)
        self.lbl_skip.setGeometry(QtCore.QRect(700, 470, 251, 41))
        self.lbl_skip.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"color:black;\n"
" background-color:white;")
        self.lbl_skip.setText("")
        self.lbl_skip.setObjectName("lbl_skip")

        self.retranslateUi(dna_seaching)
        QtCore.QMetaObject.connectSlotsByName(dna_seaching)

    def retranslateUi(self, dna_seaching):
        _translate = QtCore.QCoreApplication.translate
        dna_seaching.setWindowTitle(_translate("dna_seaching", "DNA Searching Algorithms"))
        self.btn_browse.setText(_translate("dna_seaching", "Browse"))
        self.label_7.setText(_translate("dna_seaching", "Skip"))
        self.label.setText(_translate("dna_seaching", "Input DNA Sequence:"))
        self.label_6.setText(_translate("dna_seaching", "ALignments"))
        self.label_3.setText(_translate("dna_seaching", "Enter the pattern:"))
        self.label_5.setText(_translate("dna_seaching", "Index"))
        self.label_2.setText(_translate("dna_seaching", "Choose Algorithm:"))
        self.cbox_algorithm.setItemText(0, _translate("dna_seaching", "Naive"))
        self.cbox_algorithm.setItemText(1, _translate("dna_seaching", "Boyer Moore"))
        self.cbox_algorithm.setItemText(2, _translate("dna_seaching", "SuffixArray"))
        self.cbox_algorithm.setItemText(3, _translate("dna_seaching", "K-Mer"))
        self.cbox_algorithm.setItemText(4, _translate("dna_seaching", "KMP"))
        self.cbox_algorithm.setItemText(5, _translate("dna_seaching", "approximate"))
        self.cbox_algorithm.setItemText(6, _translate("dna_seaching", "DNA reverse"))
        self.cbox_algorithm.setItemText(7, _translate("dna_seaching", "DNA Translation"))
        self.label_4.setText(_translate("dna_seaching", "  Output:"))
        self.btn_apply.setText(_translate("dna_seaching", "Apply Algorithm"))
